[req]
default_bits       = 2048
default_md         = sha256
distinguished_name = req_distinguished_name
req_extensions     = v3_req
prompt            = no

[req_distinguished_name]
C  = SG
ST = Singapore
L  = Singapore
O  = Laragon
OU = Server
CN = laragon

[v3_req]
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
IP.1  = 127.0.0.1

# You can another DNS below. For example:
# DNS.2 = xxx
# DNS.3 = yyy
IP.2 = 10.49.30.179
DNS.2 = backend-library.test
DNS.3 = *.backend-library.test
DNS.4 = backend-monitorban-laravel.test
DNS.5 = *.backend-monitorban-laravel.test
DNS.6 = backend-patient.test
DNS.7 = *.backend-patient.test
DNS.8 = coombsville.test
DNS.9 = *.coombsville.test
DNS.10 = gandom-new-frontend.test
DNS.11 = *.gandom-new-frontend.test
DNS.12 = test.test
DNS.13 = *.test.test
DNS.14 = trader-robat-app.test
DNS.15 = *.trader-robat-app.test
DNS.16 = *.localhost
DNS.17 = *.test

